### ISSUE TITLE
FreeCAD air cube is not at the same location after exporting using this macro

### ISSUE THREAD

**Issue by Basilisvirus** [LubomirJagos/FreeCAD-OpenEMS-Export#45]
When I use the FreeCAD-OpenEMS-Export macro in FreeCAD and my "openEMS_simulation" is created:  
![{D45129CB-59F6-4EC5-BE67-D61CDE56A86A}](https://github.com/user-attachments/assets/f0f6ac97-62a7-4e08-81c2-a132c21174e2)  
And then I open the .py file to run the simulation, I see that the air cube I made for the simulation, is not as seen in FreeCAD:  
![image](https://github.com/user-attachments/assets/a86d0ce6-623b-48c0-aa18-59386ca67fb6)  

My versions of software are:  
-Python 3.11.9  
-Matplotlib Version: 3.9.2  
-h5py: Version: 3.12.1  
-KiCad: Version: 8.0.5, release build
-FreeCAD: V0.21.2  
![{C43B6AE7-E003-4D56-9130-BEAE13BD4CBD}](https://github.com/user-attachments/assets/0a05987e-d989-44a3-b065-2b7a948b01f3)  
-I installed the cp311 .whl files:  
![image](https://github.com/user-attachments/assets/43f4d510-36d4-4dbf-b10f-068c504dde36)  

I do not know how to debug this further, I think this is due to incompatibilities of FreeCAD and the Macro, but cant be 100% sure. I attach the FreeCAD, macro settings and macro export files here. 
[simulationWaveProp.zip](https://github.com/user-attachments/files/17530990/simulationWaveProp.zip)

**Comment by LubomirJagos42** [comment]
some months ago I saw this problem and I think it was already repaired in FreeCAD, please try to use older version 0.20.x
in this 0.21.2 there is something wrong with STL export like position and dimension are not right exported

**Comment by Basilisvirus** [comment]
> some months ago I saw this problem and I think it was already repaired in FreeCAD, please try to use older version 0.20.x in this 0.21.2 there is something wrong with STL export like position and dimension are not right exported

You were right. Works with FreeCAD 0.20.2  

![{583D19AE-FE08-4391-9EA5-C87ED88FF27A}](https://github.com/user-attachments/assets/8444b2c0-7665-4814-b3a0-78c93ee3fafb)  

So this bug is it a known issue? like its listed in their github's issues?

**Comment by LubomirJagos42** [comment]
yes I submit at that time issue into freecad, now I found another same issue and there is that it's fixed in 0.22 but it's not backported to 0.21, therefore use 0.22 or 0.20 but would not recommend 0.21

**Comment by Basilisvirus** [comment]
@LubomirJagos42 Do you have any other versions incompatibility experience with the used tools? I think something might be wrong with my KiCad version but I am still investigating it. I also switched to Python 3.10 instead of 3.11 because of the better compatibility the examples had: 

> My versions of software are:
> ~~-Python 3.11.9~~
> -Matplotlib Version: 3.9.2
> -h5py: Version: 3.12.1
> -KiCad: Version: 8.0.5, release build
> ~~-FreeCAD: V0.21.2~~

**Comment by LubomirJagos42** [comment]
hmm, incompatibility what I'm sure will not run is to use Python 3.11, don't try 3.12, few people tried that and it's not running since CSXCAD and openEMS interface are cython code which is compiled into DLL and there is compatibility table somewhere, in short now openEMS and CSXCAD are created for python 3.11 and it's not possible to run it on 3.12
maybe if you build openEMS manualy you can make it running but at the moment out of box libs are for python 3.11, I think 3.10 is also ok

their names are:
CSXCAD.cp311-win_amd64.pyd
openEMS.cp311-win_amd64.pyd
